package com.apmsp.pmf.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("abstract_issues", "id", AbstractIssues.class);
		arp.addMapping("baseline", "id", Baseline.class);
		arp.addMapping("dashboard", "id", Dashboard.class);
		arp.addMapping("def_calendar", "id", DefCalendar.class);
		arp.addMapping("def_category", "id", DefCategory.class);
		arp.addMapping("def_currency", "id", DefCurrency.class);
		arp.addMapping("def_issues_type", "id", DefIssuesType.class);
		arp.addMapping("def_pert_factor", "id", DefPertFactor.class);
		arp.addMapping("def_priority", "id", DefPriority.class);
		arp.addMapping("def_project_phase", "id", DefProjectPhase.class);
		arp.addMapping("def_risk_type", "id", DefRiskType.class);
		arp.addMapping("def_wbs_type", "id", DefWbsType.class);
		arp.addMapping("issues_result", "id", IssuesResult.class);
		arp.addMapping("issues_seriousness", "id", IssuesSeriousness.class);
		arp.addMapping("issues_status", "id", IssuesStatus.class);
		arp.addMapping("method_cost", "id", MethodCost.class);
		arp.addMapping("method_evm", "id", MethodEvm.class);
		arp.addMapping("method_tcp", "id", MethodTcp.class);
		arp.addMapping("method_wcp", "id", MethodWcp.class);
		arp.addMapping("organization", "id", Organization.class);
		arp.addMapping("project", "id", Project.class);
		arp.addMapping("project_control_method", "id", ProjectControlMethod.class);
		arp.addMapping("project_health", "id", ProjectHealth.class);
		arp.addMapping("project_phase", "id", ProjectPhase.class);
		arp.addMapping("project_role", "id", ProjectRole.class);
		arp.addMapping("project_target", "id", ProjectTarget.class);
		arp.addMapping("risk_possibility", "id", RiskPossibility.class);
		arp.addMapping("risk_strategy", "id", RiskStrategy.class);
		arp.addMapping("system_profile", "id", SystemProfile.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("wbs", "id", Wbs.class);
		arp.addMapping("wbs_action", "id", WbsAction.class);
		arp.addMapping("wbs_schedule", "id", WbsSchedule.class);
		arp.addMapping("wbs_successor", "id", WbsSuccessor.class);
		arp.addMapping("wbs_workload", "id", WbsWorkload.class);
	}
}

