package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseAbstractIssues;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbstractIssues extends BaseAbstractIssues<AbstractIssues> {
	public static final AbstractIssues dao = new AbstractIssues();
}
