package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseBaseline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Baseline extends BaseBaseline<Baseline> {
	public static final Baseline dao = new Baseline();
}
