package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDashboard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dashboard extends BaseDashboard<Dashboard> {
	public static final Dashboard dao = new Dashboard();
}
