package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefCategory extends BaseDefCategory<DefCategory> {
	public static final DefCategory dao = new DefCategory();
}
