package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefCurrency;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefCurrency extends BaseDefCurrency<DefCurrency> {
	public static final DefCurrency dao = new DefCurrency();
}
