package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefCalendar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefCalendar extends BaseDefCalendar<DefCalendar> {
	public static final DefCalendar dao = new DefCalendar();
}
