package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefIssuesType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefIssuesType extends BaseDefIssuesType<DefIssuesType> {
	public static final DefIssuesType dao = new DefIssuesType();
}
