package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefPriority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefPriority extends BaseDefPriority<DefPriority> {
	public static final DefPriority dao = new DefPriority();
}
