package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefPertFactor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefPertFactor extends BaseDefPertFactor<DefPertFactor> {
	public static final DefPertFactor dao = new DefPertFactor();
}
