package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefProjectPhase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefProjectPhase extends BaseDefProjectPhase<DefProjectPhase> {
	public static final DefProjectPhase dao = new DefProjectPhase();
}
