package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefRiskType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefRiskType extends BaseDefRiskType<DefRiskType> {
	public static final DefRiskType dao = new DefRiskType();
}
