package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseDefWbsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DefWbsType extends BaseDefWbsType<DefWbsType> {
	public static final DefWbsType dao = new DefWbsType();
}
