package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseIssuesStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssuesStatus extends BaseIssuesStatus<IssuesStatus> {
	public static final IssuesStatus dao = new IssuesStatus();
}
