package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseIssuesSeriousness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssuesSeriousness extends BaseIssuesSeriousness<IssuesSeriousness> {
	public static final IssuesSeriousness dao = new IssuesSeriousness();
}
