package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseIssuesResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssuesResult extends BaseIssuesResult<IssuesResult> {
	public static final IssuesResult dao = new IssuesResult();
}
