package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseMethodEvm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MethodEvm extends BaseMethodEvm<MethodEvm> {
	public static final MethodEvm dao = new MethodEvm();
}
