package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseMethodTcp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MethodTcp extends BaseMethodTcp<MethodTcp> {
	public static final MethodTcp dao = new MethodTcp();
}
