package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseMethodCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MethodCost extends BaseMethodCost<MethodCost> {
	public static final MethodCost dao = new MethodCost();
}
