package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseMethodWcp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MethodWcp extends BaseMethodWcp<MethodWcp> {
	public static final MethodWcp dao = new MethodWcp();
}
