package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseOrganizationDefPriority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrganizationDefPriority extends BaseOrganizationDefPriority<OrganizationDefPriority> {
	public static final OrganizationDefPriority dao = new OrganizationDefPriority();
}
