package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseOrganization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Organization extends BaseOrganization<Organization> {
	public static final Organization dao = new Organization();
}
