package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseOrganizationDefWbsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrganizationDefWbsType extends BaseOrganizationDefWbsType<OrganizationDefWbsType> {
	public static final OrganizationDefWbsType dao = new OrganizationDefWbsType();
}
