package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProfileDefCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProfileDefCategory extends BaseProfileDefCategory<ProfileDefCategory> {
	public static final ProfileDefCategory dao = new ProfileDefCategory();
}
