package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectHealth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectHealth extends BaseProjectHealth<ProjectHealth> {
	public static final ProjectHealth dao = new ProjectHealth();
}
