package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectRole extends BaseProjectRole<ProjectRole> {
	public static final ProjectRole dao = new ProjectRole();
}
