package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectTarget;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectTarget extends BaseProjectTarget<ProjectTarget> {
	public static final ProjectTarget dao = new ProjectTarget();
}
