package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectProjectRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectProjectRole extends BaseProjectProjectRole<ProjectProjectRole> {
	public static final ProjectProjectRole dao = new ProjectProjectRole();
}
