package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectPhase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectPhase extends BaseProjectPhase<ProjectPhase> {
	public static final ProjectPhase dao = new ProjectPhase();
}
