package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectProjectPhase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectProjectPhase extends BaseProjectProjectPhase<ProjectProjectPhase> {
	public static final ProjectProjectPhase dao = new ProjectProjectPhase();
}
