package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectBaseline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectBaseline extends BaseProjectBaseline<ProjectBaseline> {
	public static final ProjectBaseline dao = new ProjectBaseline();
}
