package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectDashboard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectDashboard extends BaseProjectDashboard<ProjectDashboard> {
	public static final ProjectDashboard dao = new ProjectDashboard();
}
