package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectProjectHealth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectProjectHealth extends BaseProjectProjectHealth<ProjectProjectHealth> {
	public static final ProjectProjectHealth dao = new ProjectProjectHealth();
}
