package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectProjectTarget;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectProjectTarget extends BaseProjectProjectTarget<ProjectProjectTarget> {
	public static final ProjectProjectTarget dao = new ProjectProjectTarget();
}
