package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseProjectControlMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectControlMethod extends BaseProjectControlMethod<ProjectControlMethod> {
	public static final ProjectControlMethod dao = new ProjectControlMethod();
}
