package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseRiskPossibility;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RiskPossibility extends BaseRiskPossibility<RiskPossibility> {
	public static final RiskPossibility dao = new RiskPossibility();
}
