package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseRiskStrategy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RiskStrategy extends BaseRiskStrategy<RiskStrategy> {
	public static final RiskStrategy dao = new RiskStrategy();
}
