package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseSystemProfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemProfile extends BaseSystemProfile<SystemProfile> {
	public static final SystemProfile dao = new SystemProfile();
}
