package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task();
}
