package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseUserProjectWbs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProjectWbs extends BaseUserProjectWbs<UserProjectWbs> {
	public static final UserProjectWbs dao = new UserProjectWbs();
}
