package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseWbs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wbs extends BaseWbs<Wbs> {
	public static final Wbs dao = new Wbs();
}
