package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseWbsAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WbsAction extends BaseWbsAction<WbsAction> {
	public static final WbsAction dao = new WbsAction();
}
