package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseWbsSuccessor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WbsSuccessor extends BaseWbsSuccessor<WbsSuccessor> {
	public static final WbsSuccessor dao = new WbsSuccessor();
}
