package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseWbsSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WbsSchedule extends BaseWbsSchedule<WbsSchedule> {
	public static final WbsSchedule dao = new WbsSchedule();
}
