package com.apmsp.pmf.model;

import com.apmsp.pmf.model.base.BaseWbsWorkload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WbsWorkload extends BaseWbsWorkload<WbsWorkload> {
	public static final WbsWorkload dao = new WbsWorkload();
}
