package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectProjectPhase<M extends BaseProjectProjectPhase<M>> extends Model<M> implements IBean {

	public void setProjectProjectPhasesId(java.lang.Long projectProjectPhasesId) {
		set("project_project_phases_id", projectProjectPhasesId);
	}

	public java.lang.Long getProjectProjectPhasesId() {
		return get("project_project_phases_id");
	}

	public void setProjectPhaseId(java.lang.Long projectPhaseId) {
		set("project_phase_id", projectPhaseId);
	}

	public java.lang.Long getProjectPhaseId() {
		return get("project_phase_id");
	}

}
