package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectProjectTarget<M extends BaseProjectProjectTarget<M>> extends Model<M> implements IBean {

	public void setProjectProjectTargetsId(java.lang.Long projectProjectTargetsId) {
		set("project_project_targets_id", projectProjectTargetsId);
	}

	public java.lang.Long getProjectProjectTargetsId() {
		return get("project_project_targets_id");
	}

	public void setProjectTargetId(java.lang.Long projectTargetId) {
		set("project_target_id", projectTargetId);
	}

	public java.lang.Long getProjectTargetId() {
		return get("project_target_id");
	}

}
