package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbstractIssues<M extends BaseAbstractIssues<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setBid(java.lang.String bid) {
		set("bid", bid);
	}

	public java.lang.String getBid() {
		return get("bid");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setCreatorId(java.lang.Long creatorId) {
		set("creator_id", creatorId);
	}

	public java.lang.Long getCreatorId() {
		return get("creator_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIssuesResultId(java.lang.Long issuesResultId) {
		set("issues_result_id", issuesResultId);
	}

	public java.lang.Long getIssuesResultId() {
		return get("issues_result_id");
	}

	public void setIssuesSeriousnessId(java.lang.Long issuesSeriousnessId) {
		set("issues_seriousness_id", issuesSeriousnessId);
	}

	public java.lang.Long getIssuesSeriousnessId() {
		return get("issues_seriousness_id");
	}

	public void setModifiedDate(java.util.Date modifiedDate) {
		set("modified_date", modifiedDate);
	}

	public java.util.Date getModifiedDate() {
		return get("modified_date");
	}

	public void setModifierId(java.lang.Long modifierId) {
		set("modifier_id", modifierId);
	}

	public java.lang.Long getModifierId() {
		return get("modifier_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setResponsibleUserId(java.lang.Long responsibleUserId) {
		set("responsible_user_id", responsibleUserId);
	}

	public java.lang.Long getResponsibleUserId() {
		return get("responsible_user_id");
	}

	public void setSpecificMeasures(java.lang.String specificMeasures) {
		set("specific_measures", specificMeasures);
	}

	public java.lang.String getSpecificMeasures() {
		return get("specific_measures");
	}

	public void setStatusId(java.lang.Long statusId) {
		set("status_id", statusId);
	}

	public java.lang.Long getStatusId() {
		return get("status_id");
	}

	public void setWbsId(java.lang.Long wbsId) {
		set("wbs_id", wbsId);
	}

	public java.lang.Long getWbsId() {
		return get("wbs_id");
	}

	public void setClazz(java.lang.String clazz) {
		set("clazz", clazz);
	}

	public java.lang.String getClazz() {
		return get("clazz");
	}

	public void setEffect(java.lang.String effect) {
		set("effect", effect);
	}

	public java.lang.String getEffect() {
		return get("effect");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public void setRepresent(java.lang.String represent) {
		set("represent", represent);
	}

	public java.lang.String getRepresent() {
		return get("represent");
	}

	public void setRiskStragegySelfDef(java.lang.String riskStragegySelfDef) {
		set("risk_stragegy_self_def", riskStragegySelfDef);
	}

	public java.lang.String getRiskStragegySelfDef() {
		return get("risk_stragegy_self_def");
	}

	public void setRiskStrategyId(java.lang.Long riskStrategyId) {
		set("risk_strategy_id", riskStrategyId);
	}

	public java.lang.Long getRiskStrategyId() {
		return get("risk_strategy_id");
	}

	public void setRiskTypeId(java.lang.Long riskTypeId) {
		set("risk_type_id", riskTypeId);
	}

	public java.lang.Long getRiskTypeId() {
		return get("risk_type_id");
	}

	public void setRiskTypeSelfDef(java.lang.String riskTypeSelfDef) {
		set("risk_type_self_def", riskTypeSelfDef);
	}

	public java.lang.String getRiskTypeSelfDef() {
		return get("risk_type_self_def");
	}

	public void setRiskpossibilityId(java.lang.Long riskpossibilityId) {
		set("riskpossibility_id", riskpossibilityId);
	}

	public java.lang.Long getRiskpossibilityId() {
		return get("riskpossibility_id");
	}

}
