package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrganization<M extends BaseOrganization<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setBStatus(java.lang.String bStatus) {
		set("b_status", bStatus);
	}

	public java.lang.String getBStatus() {
		return get("b_status");
	}

	public void setBid(java.lang.String bid) {
		set("bid", bid);
	}

	public java.lang.String getBid() {
		return get("bid");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setCreatorId(java.lang.Long creatorId) {
		set("creator_id", creatorId);
	}

	public java.lang.Long getCreatorId() {
		return get("creator_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIsActived(java.lang.Boolean isActived) {
		set("is_actived", isActived);
	}

	public java.lang.Boolean getIsActived() {
		return get("is_actived");
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}

	public void setLastSavedDate(java.util.Date lastSavedDate) {
		set("last_saved_date", lastSavedDate);
	}

	public java.util.Date getLastSavedDate() {
		return get("last_saved_date");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setProfileId(java.lang.Long profileId) {
		set("profile_id", profileId);
	}

	public java.lang.Long getProfileId() {
		return get("profile_id");
	}

}
