package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectBaseline<M extends BaseProjectBaseline<M>> extends Model<M> implements IBean {

	public void setProjectBaselinesId(java.lang.Long projectBaselinesId) {
		set("project_baselines_id", projectBaselinesId);
	}

	public java.lang.Long getProjectBaselinesId() {
		return get("project_baselines_id");
	}

	public void setBaselineId(java.lang.Long baselineId) {
		set("baseline_id", baselineId);
	}

	public java.lang.Long getBaselineId() {
		return get("baseline_id");
	}

}
