package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWbsSuccessor<M extends BaseWbsSuccessor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setDays(java.lang.Float days) {
		set("days", days);
	}

	public java.lang.Float getDays() {
		return get("days");
	}

	public void setPredecessorId(java.lang.Long predecessorId) {
		set("predecessor_id", predecessorId);
	}

	public java.lang.Long getPredecessorId() {
		return get("predecessor_id");
	}

	public void setRelationship(java.lang.Integer relationship) {
		set("relationship", relationship);
	}

	public java.lang.Integer getRelationship() {
		return get("relationship");
	}

	public void setSuccessorId(java.lang.Long successorId) {
		set("successor_id", successorId);
	}

	public java.lang.Long getSuccessorId() {
		return get("successor_id");
	}

}
