package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectProjectRole<M extends BaseProjectProjectRole<M>> extends Model<M> implements IBean {

	public void setProjectProjectRolesId(java.lang.Long projectProjectRolesId) {
		set("project_project_roles_id", projectProjectRolesId);
	}

	public java.lang.Long getProjectProjectRolesId() {
		return get("project_project_roles_id");
	}

	public void setProjectRoleId(java.lang.Long projectRoleId) {
		set("project_role_id", projectRoleId);
	}

	public java.lang.Long getProjectRoleId() {
		return get("project_role_id");
	}

}
