package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setActualCost(java.lang.Float actualCost) {
		set("actual_cost", actualCost);
	}

	public java.lang.Float getActualCost() {
		return get("actual_cost");
	}

	public void setActualDuration(java.lang.Float actualDuration) {
		set("actual_duration", actualDuration);
	}

	public java.lang.Float getActualDuration() {
		return get("actual_duration");
	}

	public void setActualFinish(java.util.Date actualFinish) {
		set("actual_finish", actualFinish);
	}

	public java.util.Date getActualFinish() {
		return get("actual_finish");
	}

	public void setActualOvertimeCost(java.lang.Float actualOvertimeCost) {
		set("actual_overtime_cost", actualOvertimeCost);
	}

	public java.lang.Float getActualOvertimeCost() {
		return get("actual_overtime_cost");
	}

	public void setActualOvertimeWork(java.lang.Float actualOvertimeWork) {
		set("actual_overtime_work", actualOvertimeWork);
	}

	public java.lang.Float getActualOvertimeWork() {
		return get("actual_overtime_work");
	}

	public void setActualStart(java.util.Date actualStart) {
		set("actual_start", actualStart);
	}

	public java.util.Date getActualStart() {
		return get("actual_start");
	}

	public void setActualWork(java.lang.Float actualWork) {
		set("actual_work", actualWork);
	}

	public java.lang.Float getActualWork() {
		return get("actual_work");
	}

	public void setBid(java.lang.String bid) {
		set("bid", bid);
	}

	public java.lang.String getBid() {
		return get("bid");
	}

	public void setCost(java.lang.Float cost) {
		set("cost", cost);
	}

	public java.lang.Float getCost() {
		return get("cost");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCritical(java.lang.Boolean critical) {
		set("critical", critical);
	}

	public java.lang.Boolean getCritical() {
		return get("critical");
	}

	public void setDeadline(java.util.Date deadline) {
		set("deadline", deadline);
	}

	public java.util.Date getDeadline() {
		return get("deadline");
	}

	public void setDuration(java.lang.Float duration) {
		set("duration", duration);
	}

	public java.lang.Float getDuration() {
		return get("duration");
	}

	public void setDurationFormat(java.lang.Integer durationFormat) {
		set("duration_format", durationFormat);
	}

	public java.lang.Integer getDurationFormat() {
		return get("duration_format");
	}

	public void setFinish(java.util.Date finish) {
		set("finish", finish);
	}

	public java.util.Date getFinish() {
		return get("finish");
	}

	public void setMilestone(java.lang.Boolean milestone) {
		set("milestone", milestone);
	}

	public java.lang.Boolean getMilestone() {
		return get("milestone");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setOverAllocated(java.lang.Boolean overAllocated) {
		set("over_allocated", overAllocated);
	}

	public java.lang.Boolean getOverAllocated() {
		return get("over_allocated");
	}

	public void setOvertimeCost(java.lang.Float overtimeCost) {
		set("overtime_cost", overtimeCost);
	}

	public java.lang.Float getOvertimeCost() {
		return get("overtime_cost");
	}

	public void setOvertimeWork(java.lang.Float overtimeWork) {
		set("overtime_work", overtimeWork);
	}

	public java.lang.Float getOvertimeWork() {
		return get("overtime_work");
	}

	public void setParentTaskId(java.lang.Long parentTaskId) {
		set("parent_task_id", parentTaskId);
	}

	public java.lang.Long getParentTaskId() {
		return get("parent_task_id");
	}

	public void setPercentComplete(java.lang.Float percentComplete) {
		set("percent_complete", percentComplete);
	}

	public java.lang.Float getPercentComplete() {
		return get("percent_complete");
	}

	public void setPercentWorkComplete(java.lang.Float percentWorkComplete) {
		set("percent_work_complete", percentWorkComplete);
	}

	public java.lang.Float getPercentWorkComplete() {
		return get("percent_work_complete");
	}

	public void setPreDecessorLinkId(java.lang.Long preDecessorLinkId) {
		set("pre_decessor_link_id", preDecessorLinkId);
	}

	public java.lang.Long getPreDecessorLinkId() {
		return get("pre_decessor_link_id");
	}

	public void setPriorityId(java.lang.Long priorityId) {
		set("priority_id", priorityId);
	}

	public java.lang.Long getPriorityId() {
		return get("priority_id");
	}

	public void setProjectId(java.lang.Long projectId) {
		set("project_id", projectId);
	}

	public java.lang.Long getProjectId() {
		return get("project_id");
	}

	public void setRecurring(java.lang.Boolean recurring) {
		set("recurring", recurring);
	}

	public java.lang.Boolean getRecurring() {
		return get("recurring");
	}

	public void setRegularWork(java.lang.Float regularWork) {
		set("regular_work", regularWork);
	}

	public java.lang.Float getRegularWork() {
		return get("regular_work");
	}

	public void setRemainingCost(java.lang.Float remainingCost) {
		set("remaining_cost", remainingCost);
	}

	public java.lang.Float getRemainingCost() {
		return get("remaining_cost");
	}

	public void setRemainingDuration(java.lang.Float remainingDuration) {
		set("remaining_duration", remainingDuration);
	}

	public java.lang.Float getRemainingDuration() {
		return get("remaining_duration");
	}

	public void setRemainingOvertimeCost(java.lang.Float remainingOvertimeCost) {
		set("remaining_overtime_cost", remainingOvertimeCost);
	}

	public java.lang.Float getRemainingOvertimeCost() {
		return get("remaining_overtime_cost");
	}

	public void setRemainingOvertimeWork(java.lang.Float remainingOvertimeWork) {
		set("remaining_overtime_work", remainingOvertimeWork);
	}

	public java.lang.Float getRemainingOvertimeWork() {
		return get("remaining_overtime_work");
	}

	public void setRemainingWork(java.lang.Float remainingWork) {
		set("remaining_work", remainingWork);
	}

	public java.lang.Float getRemainingWork() {
		return get("remaining_work");
	}

	public void setResponsibleUserId(java.lang.Long responsibleUserId) {
		set("responsible_user_id", responsibleUserId);
	}

	public java.lang.Long getResponsibleUserId() {
		return get("responsible_user_id");
	}

	public void setResume(java.util.Date resume) {
		set("resume", resume);
	}

	public java.util.Date getResume() {
		return get("resume");
	}

	public void setResumeValid(java.lang.Boolean resumeValid) {
		set("resume_valid", resumeValid);
	}

	public java.lang.Boolean getResumeValid() {
		return get("resume_valid");
	}

	public void setShouldComplete(java.lang.Float shouldComplete) {
		set("should_complete", shouldComplete);
	}

	public java.lang.Float getShouldComplete() {
		return get("should_complete");
	}

	public void setShouldWorkComplete(java.lang.Float shouldWorkComplete) {
		set("should_work_complete", shouldWorkComplete);
	}

	public java.lang.Float getShouldWorkComplete() {
		return get("should_work_complete");
	}

	public void setStart(java.util.Date start) {
		set("start", start);
	}

	public java.util.Date getStart() {
		return get("start");
	}

	public void setStop(java.util.Date stop) {
		set("stop", stop);
	}

	public java.util.Date getStop() {
		return get("stop");
	}

	public void setSummary(java.lang.Boolean summary) {
		set("summary", summary);
	}

	public java.lang.Boolean getSummary() {
		return get("summary");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setWbsActionId(java.lang.Long wbsActionId) {
		set("wbs_action_id", wbsActionId);
	}

	public java.lang.Long getWbsActionId() {
		return get("wbs_action_id");
	}

	public void setWork(java.lang.Float work) {
		set("work", work);
	}

	public java.lang.Float getWork() {
		return get("work");
	}

}
