package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDefPertFactor<M extends BaseDefPertFactor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setBid(java.lang.String bid) {
		set("bid", bid);
	}

	public java.lang.String getBid() {
		return get("bid");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIsSystemSetting(java.lang.Boolean isSystemSetting) {
		set("is_system_setting", isSystemSetting);
	}

	public java.lang.Boolean getIsSystemSetting() {
		return get("is_system_setting");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOptimisticValue(java.lang.Float optimisticValue) {
		set("optimistic_value", optimisticValue);
	}

	public java.lang.Float getOptimisticValue() {
		return get("optimistic_value");
	}

	public void setOrganizationId(java.lang.Long organizationId) {
		set("organization_id", organizationId);
	}

	public java.lang.Long getOrganizationId() {
		return get("organization_id");
	}

	public void setPessimisticValue(java.lang.Float pessimisticValue) {
		set("pessimistic_value", pessimisticValue);
	}

	public java.lang.Float getPessimisticValue() {
		return get("pessimistic_value");
	}

	public void setPossibleValue(java.lang.Float possibleValue) {
		set("possible_value", possibleValue);
	}

	public java.lang.Float getPossibleValue() {
		return get("possible_value");
	}

	public void setProjectId(java.lang.Long projectId) {
		set("project_id", projectId);
	}

	public java.lang.Long getProjectId() {
		return get("project_id");
	}

}
