package com.apmsp.pmf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectProjectHealth<M extends BaseProjectProjectHealth<M>> extends Model<M> implements IBean {

	public void setProjectProjectHealthId(java.lang.Long projectProjectHealthId) {
		set("project_project_health_id", projectProjectHealthId);
	}

	public java.lang.Long getProjectProjectHealthId() {
		return get("project_project_health_id");
	}

	public void setProjectHealthId(java.lang.Long projectHealthId) {
		set("project_health_id", projectHealthId);
	}

	public java.lang.Long getProjectHealthId() {
		return get("project_health_id");
	}

}
